### ISSUE TITLE
Certain time addition links are broken

### ISSUE THREAD

**Issue by jmk520** [jobbogamer/kartbucket#3]
**Description**

When attempting to add my time for **_Wario's Galleon_** it is bringing up the box for **_Alpine Pass_**. Unsure if this was a textual error, I entered a time. This modified my time for **_Alpine Pass_** instead, and when attempting to change it back I can not, because my time for **_Alpine Pass_** is slower than the time currently entered.

**Steps to reproduce**

1. Click the pencil icon for the **_Wario's Galleon_** level for JK
2. Problem is visible on screen, but entering a time and submitting will show more clearly

**Expected behaviour**

- The time entered should appear in the **_Wario's Galleon_** row of the table

**Actual behaviour**

- The time entered appears in the **_Alpine Pass_** row of the table

**Version**

Kartbucket is not currently versioned.

**Reproducibility**

Every time.

**Comment by jobbogamer** [comment]
This is now being tracked as #4.
